# Generated by Django 4.1.1 on 2023-02-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='')),
                ('Country', models.CharField(max_length=20, verbose_name='Страна')),
                ('Metal', models.CharField(max_length=50, verbose_name='Металл')),
                ('Year', models.IntegerField(verbose_name='Номинал')),
                ('Text', models.TextField(max_length=250, verbose_name='Описание')),
            ],
        ),
    ]
