# Generated by Django 4.1.1 on 2023-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneys', '0002_article_image_two_alter_article_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Image',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Image_two',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
