# Generated by Django 4.1.1 on 2023-03-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneys', '0003_alter_article_image_alter_article_image_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Nominal',
            field=models.IntegerField(null=True, verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Year',
            field=models.IntegerField(null=True, verbose_name='Год выпуска монеты'),
        ),
    ]
